
name: Java CI with Maven

on:
  push:
    branches: [ "v0.2" ]
  pull_request:
    branches: [ "v0.2" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: GitHub Action for GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: latest
        java-version: 17
        components: native-image,python,llvm
        cache: maven
        native-image-musl: true
    - name: Build with Maven
      run: mvn package -P native --file pom.xml
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
